function getLastSnapshotID(doc) {
  var hsObj = doc.historyStates;
  var hsLength = hsObj.length;
  for (var i = hsLength-1; i > -1; i--) {
    if(hsObj[i].snapshot) {
      return i;
    }
  }
}

function takeSnapshot(doc) {
  var desc153 = new ActionDescriptor();
  var ref119 = new ActionReference();
  ref119.putClass(charIDToTypeID("SnpS")); // Snapshot
  desc153.putReference(charIDToTypeID("null"), ref119 );
  var ref120 = new ActionReference();
  ref120.putProperty(charIDToTypeID("HstS"), charIDToTypeID("CrnH") ); // Historystate, CurrentHistorystate
  desc153.putReference(charIDToTypeID("From"), ref120 ); // From Current Historystate
  executeAction(charIDToTypeID("Mk  "), desc153, DialogModes.NO );
  return getLastSnapshotID(doc);
}

function revertToSnapshot(doc, snapshotID) {
  doc.activeHistoryState = doc.historyStates[snapshotID];
}
// Generated by CoffeeScript 1.9.1
(function() {
  var allLayer, folder, main, outputLayer, setup;

  folder = null;

  setup = function() {
    preferences.rulerUnits = Units.PIXELS;
    if (app.documents.length === 0) {
      alert('cannot access document');
      return false;
    }
    folder = Folder.selectDialog("保存先フォルダの選択");
    if (folder === null) {
      return false;
    }
    return true;
  };

  allLayer = function(root) {
    var i, layer, len, list, ref, set;
    list = (function() {
      var i, len, ref, results;
      ref = root.artLayers;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        layer = ref[i];
        if (!layer.visible) {
          continue;
        }
        layer.visible = false;
        results.push(layer);
      }
      return results;
    })();
    ref = root.layerSets;
    for (i = 0, len = ref.length; i < len; i++) {
      set = ref[i];
      if (set.visible) {
        list = list.concat(allLayer(set, false));
      }
    }
    return list;
  };

  main = function() {
    var copiedDoc, i, len, snapShotId, target, targets;
    copiedDoc = app.activeDocument.duplicate(activeDocument.name.slice(0, -4) + '.copy.psd');
    targets = allLayer(copiedDoc);
    snapShotId = takeSnapshot(copiedDoc);
    for (i = 0, len = targets.length; i < len; i++) {
      target = targets[i];
      outputLayer(copiedDoc, target);
      revertToSnapshot(copiedDoc, snapShotId);
    }
    return copiedDoc.close(SaveOptions.DONOTSAVECHANGES);
  };

  outputLayer = function(doc, layer) {
    var pngSaveOptions, saveFile;
    layer.visible = true;
    if (!layer.isBackgroundLayer) {
      doc.trim(TrimType.TRANSPARENT);
    }
    saveFile = new File(folder.fsName + "/" + layer.name + ".png");
    pngSaveOptions = new PNGSaveOptions();
    return doc.saveAs(saveFile, pngSaveOptions, true, Extension.LOWERCASE);
  };

  if (setup()) {
    main();
    alert('complete!');
  }

}).call(this);
